### ISSUE TITLE
Fingerprinting?

### ISSUE THREAD

**Issue by torgo** [w3ctag/secure-the-web#1]
Should we be considering "fingerprinting" under the category of security and securing the Web?  Fingerprinting is arguably an architectural issue - is there anything that the web platform can do to address the risk of finger printing across the api surface? There are mechanisms to mitigate fingerprinting - could this go into a recommendation from the TAG?

**Comment by hadleybeeman** [comment]
Superseded by the [Security and Privacy questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/) and PiNG's work on [anti-fingerprinting guidance](https://www.w3.org/TR/fingerprinting-guidance/).
