### ISSUE TITLE
Talk about sandboxed iframes

### ISSUE THREAD

**Issue by DavidBruant** [w3ctag/secure-the-web#5]
The way iframes are [spec'ed today](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-iframe-element.html#the-iframe-element) is terrible since it's the _de facto_ standardization of what browsers actually implemented.
Sandboxed iframes are a more modular and saner approach to iframes. The web would probably be more secure (and incidentally more performance eventually) if the iframes were more sandboxed.

**Comment by torgo** [comment]
This work has been folded into other work including the securing the web finding. This repo is obsolete. Additional web security work is always ongoing in the [web app sec](https://github.com/w3c/webappsec) group and we encourage you to engage there.
